var GAMES_DATA = {
  "games": [
    { "id": 1, "title": "Metal Gear Solid", "image": "metalgearsolid.png" },
    { "id": 2, "title": "Final Fantasy VII", "image": "finalfantasy7.png" },
    { "id": 3, "title": "Castlevania: Symphony of the Night", "image": "castlevaniasotn.png" },
    { "id": 4, "title": "Resident Evil 2", "image": "residentevil2.png" },
    { "id": 5, "title": "Tekken 3", "image": "tekken3.png" },
    { "id": 6, "title": "Gran Turismo", "image": "granturismo.png" },
    { "id": 7, "title": "Gran Turismo 2", "image": "granturismo2.png" },
    { "id": 8, "title": "Tony Hawk's Pro Skater 2", "image": "tonyhawkproskater2.png" },
    { "id": 9, "title": "Silent Hill", "image": "silenthill.png" },
    { "id": 10, "title": "Crash Bandicoot: Warped", "image": "crashbandicootwarped.png" },
    { "id": 11, "title": "Crash Team Racing", "image": "crashteamracing.png" },
    { "id": 12, "title": "Spyro the Dragon", "image": "spyrothedragon.png" },
    { "id": 13, "title": "Spyro 2: Ripto's Rage!", "image": "spyro2.png" },
    { "id": 14, "title": "Final Fantasy IX", "image": "finalfantasy9.png" },
    { "id": 15, "title": "Final Fantasy VIII", "image": "finalfantasy8.png" },
    { "id": 16, "title": "Chrono Cross", "image": "chronocross.png" },
    { "id": 17, "title": "Vagrant Story", "image": "vagrantstory.png" },
    { "id": 18, "title": "Xenogears", "image": "xenogears.png" },
    { "id": 19, "title": "Suikoden II", "image": "suikoden2.png" },
    { "id": 20, "title": "Ape Escape", "image": "apeescape.png" },
    { "id": 21, "title": "Tomb Raider", "image": "tombraider.png" },
    { "id": 22, "title": "Tomb Raider II", "image": "tombraider2.png" },
    { "id": 23, "title": "Legacy of Kain: Soul Reaver", "image": "soulreaver.png" },
    { "id": 24, "title": "Oddworld: Abe's Oddysee", "image": "oddworldabesoddysee.png" },
    { "id": 25, "title": "Oddworld: Abe's Exoddus", "image": "oddworldabesexoddus.png" },
    { "id": 26, "title": "Rayman", "image": "rayman.png" },
    { "id": 27, "title": "Rayman 2: The Great Escape", "image": "rayman2.png" },
    { "id": 28, "title": "MediEvil", "image": "medievil.png" },
    { "id": 29, "title": "Klonoa: Door to Phantomile", "image": "klonoa.png" },
    { "id": 30, "title": "PaRappa the Rapper", "image": "parappatherapper.png" },
    { "id": 31, "title": "R4: Ridge Racer Type 4", "image": "ridgeracertype4.png" },
    { "id": 32, "title": "Wipeout XL", "image": "wipeoutxl.png" },
    { "id": 33, "title": "Wipeout 3", "image": "wipeout3.png" },
    { "id": 34, "title": "Driver", "image": "driver.png" },
    { "id": 35, "title": "Driver 2", "image": "driver2.png" },
    { "id": 36, "title": "Dino Crisis", "image": "dinocrisis.png" },
    { "id": 37, "title": "Dino Crisis 2", "image": "dinocrisis2.png" },
    { "id": 38, "title": "Resident Evil", "image": "residentevil.png" },
    { "id": 39, "title": "Resident Evil 3: Nemesis", "image": "residentevil3.png" },
    { "id": 40, "title": "Parasite Eve", "image": "parasiteeve.png" },
    { "id": 41, "title": "Parasite Eve II", "image": "parasiteeve2.png" },
    { "id": 42, "title": "Syphon Filter", "image": "syphonfilter.png" },
    { "id": 43, "title": "Syphon Filter 2", "image": "syphonfilter2.png" },
    { "id": 44, "title": "Tenchu: Stealth Assassins", "image": "tenchu.png" },
    { "id": 45, "title": "Tenchu 2: Birth of the Stealth Assassins", "image": "tenchu2.png" },
    { "id": 46, "title": "Twisted Metal 2", "image": "twistedmetal2.png" },
    { "id": 47, "title": "Street Fighter Alpha 3", "image": "streetfighteralpha3.png" },
    { "id": 48, "title": "Marvel vs. Capcom: Clash of Super Heroes", "image": "marvelvscapcom.png" },
    { "id": 49, "title": "Tekken 2", "image": "tekken2.png" },
    { "id": 50, "title": "Soul Blade", "image": "soulblade.png" },
    { "id": 51, "title": "Bushido Blade", "image": "bushidoblade.png" },
    { "id": 52, "title": "Tony Hawk's Pro Skater", "image": "tonyhawkproskater.png" },
    { "id": 53, "title": "Tony Hawk's Pro Skater 3", "image": "tonyhawkproskater3.png" },
    { "id": 54, "title": "Colin McRae Rally 2.0", "image": "colinmcraerally2.png" },
    { "id": 55, "title": "Need for Speed III: Hot Pursuit", "image": "needforspeed3.png" },
    { "id": 56, "title": "Need for Speed: High Stakes", "image": "needforspeedhighstakes.png" },
    { "id": 57, "title": "The Legend of Dragoon", "image": "legendofdragoon.png" },
    { "id": 58, "title": "Wild Arms", "image": "wildarms.png" },
    { "id": 59, "title": "Lunar: Silver Star Story Complete", "image": "lunarsilverstarstory.png" },
    { "id": 60, "title": "Alundra", "image": "alundra.png" },
    { "id": 61, "title": "Tomba!", "image": "tomba.png" },
    { "id": 62, "title": "Mega Man Legends", "image": "megamanlegends.png" },
    { "id": 63, "title": "Armored Core", "image": "armoredcore.png" },
    { "id": 64, "title": "Front Mission 3", "image": "frontmission3.png" }
  ]
};
